### ISSUE TITLE
about the format of text8.zip and code

### ISSUE THREAD

**Issue by zhangyixinSarah** [futureUnsure/word2vec-visualizer#1]
Dear, I have 2 questions. 1. what is the initial format of text8.zip before it was compressed? 2. if I want to change text8.zip with my own file, such as myfile.txt, myfile.model, or myfile.vector, how should the code to be changed? Because I have trained my text in another python, and it generate a model file and a vector file. Thanks~
name: Sarah
email: sarahzyxll@outlook.com

![word2vec](https://user-images.githubusercontent.com/56244274/149085841-998e6a27-add6-4f99-a563-ffd4e1b72733.png)

**Comment by futureUnsure** [comment]
@zhangyixinSarah  Apologies for the late reply! I think you might have already got a resolution on that by now. But on the off chance that you have not, let me answer your queries.

I'm not sure about the format of `text8.zip` before compression, it is a widely used dataset for NLP purposes hosted  [here](http://mattmahoney.net/dc)

Now, the error you see on your machine, is because of a mismatch in number of bytes you use in your method call and the number of bytes `maybe_download` expects.

To fix that, I suggest you
- either replace `31344016` with the actual number of bytes in your dataset. Or
- modify `maybe_download` to remove the expectation of number of bytes matching the one provided.

Hope that helps!
